name: Testing config overrides
type: profile
description: 'Minimal profile for running tests with config overrides in a profile.'
# version: VERSION
# core: 8.x
hidden: true
dependencies:
  - action
  - language
  - tour

# Information added by Drupal.org packaging script on 2015-12-02
version: '8.0.1'
core: '8.x'
project: 'drupal'
datestamp: 1449067409
